# Generated by Django 5.0.4 on 2024-04-07 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
